import socket
import random

def client_program():
  host = socket.gethostname()                       # get the hostname
  # print("host is " + host)
  port = 53535                                      # socket server port number
  client_socket = socket.socket()                   # instantiate
  client_socket.connect((host, port))               # connect to the server
  # print(client_socket)
  print("*** Connected to server ***")
  num_c = random.randint(1, 100)                    # generating random number
  print("Random number generated by client : " + str(num_c))
  message = str(host) + "," + str(num_c)
  client_socket.send(message.encode())              # send message
  data = client_socket.recv(1024).decode()          # receive response
  # client_socket.close() # close the connection

if __name__ == '__main__':
  client_program()